#!/bin/bash
source /etc/adduser.conf
source /usr/lib/elive-tools/functions
#el_make_environment
. gettext.sh
TEXTDOMAIN="nurse"
export TEXTDOMAIN

defaultuser="eliveuser"


show_message_exit_x11(){
    local message_exit
    message_exit="$( printf "$( eval_gettext "Sorry, you need to exit from the graphical system or close the program of you like to upgrade, if you need to exit from the graphical system, you need to login in pure console ( Control-Alt-F1 from entrance and Control-Alt-F9 for return to entrance ) and with your user type: elive-skel upgrade" )" )"

    if [[ -n "$DISPLAY" && -f /usr/bin/zenity ]] ; then
        zenity --error --text="$message_exit"
    else
        echo "$message_exit"
    fi
    exit 1
}

show_message_done(){
    local message_done
    message_done="$( printf "$( eval_gettext "Upgrade done, try now to restart the application" )" )"

    if [[ -n "$DISPLAY" && -f /usr/bin/zenity ]] ; then
        zenity --info --text="$message_done"
    else
        echo "$message_done"
    fi
}

show_message_required_select(){
    if [[ -n "$DISPLAY" && -f /usr/bin/zenity ]] ; then
        zenity --info --text="$( eval_gettext "You don't have selected correctly a configuration, no upgrade done, try again." )"
    else
        echo "$( eval_gettext "You don't have selected correctly a configuration, no upgrade done, try again." )"
    fi
    exit 1
}


upgradegraphical(){
    # return if we have conf
    [[ -n "$2" ]] && return

    # improve this crap
    nameconf="$( ls -a /etc/skel | egrep "\\." | egrep -v "\\.$" | zenity --list --text="$( eval_gettext "Select a personal configuration for upgrade" )" --column="$( eval_gettext "Configuration" )" || echo cancel ; )"

    [[ "$nameconf" = "cancel" ]] && exit 1
    [[ "$nameconf" = "" ]] && { show_message_required_select ; exit 1 ; }

    ps aux | grep e16 | grep -v grep | awk -v user="$USER" '$1 ~ user { print $NF }' | grep e16 && [[ "$nameconf" = ".e16" ]] && show_message_exit_x11

    ps aux | grep enlightenment | grep -v grep | awk -v user="$USER" '$1 ~ user { print $NF }' | grep enlightenment && [[ "$nameconf" = ".e" ]] && show_message_exit_x11

    ps aux | grep xchat | grep -v grep | awk -v user="$USER" '$1 ~ user { print $NF }' | grep xchat && [[ "$nameconf" = ".xchat2" ]] && show_message_exit_x11
}

upgradeconsole(){
    # return if we have conf
    [[ -n $2 ]] && return

    echo -e "Select a conf name (included the dot if any) for upgrade"
    ls -a /etc/skel/ | egrep "\\." | egrep -v "\\.$" | less

    echo -e "Enter the name of one configuration for upgrade"
    read nameconf

    [[ "$nameconf" = "" ]] && { show_message_required_select ; exit 1 ; }

    ps aux | grep e16 | grep -v grep | awk -v user="$USER" '$1 ~ user { print $NF }' | grep e16 && [[ "$nameconf" = ".e16" ]] && show_message_exit_x11
    ps aux | grep enlightenment | grep -v grep | awk -v user="$USER" '$1 ~ user { print $NF }' | grep enlightenment && [[ "$nameconf" = ".e" ]] && show_message_exit_x11
    ps aux | grep xchat | grep -v grep | awk -v user="$USER" '$1 ~ user { print $NF }' | grep xchat && [[ "$nameconf" = ".xchat2" ]] && show_message_exit_x11
}

upgradedirect(){
    unset DISPLAY
    nameconf="$2"
}

upgradefromroot(){
    local usuario direlegido
    #nameconf="$2"

    [[ "$UID" != "0" ]] && { echo -e "You need root for this option" && exit 1 ; }

    direlegido=$( awk -v usuario="$3" 'BEGIN{FS=":"}{if ($1 == usuario) print $6 }' /etc/passwd )

    if [[ -z "$direlegido" ]] || ! el_check_dirs "$direlegido" ; then
        el_error "homedir of user not found, exiting..."
        exit 1
    fi

    if [[ -z "$nameconf" ]] ; then
        el_error "nameconf empty, exiting..."
        exit 3
    fi

    rm -rf "$direlegido/$nameconf.old"
    mv "$direlegido/$nameconf" "$direlegido/$nameconf.old" # backuping the old one

    if [[ -e "/etc/skel/$nameconf" ]] ; then
        if cp -a "/etc/skel/$nameconf" "$direlegido/" ; then
            convert_dir "$3" "$direlegido/$nameconf"
        else
            el_error "Not posible to copy to the HOME dir of $3 ($direlegido)"
            exit 4
        fi
    else
        el_error "/etc/skel/$nameconf doesn't exist"
        exit 5
    fi


    case "$nameconf" in
        .config)
            # TODO: actually .config is much bigger, most of the apps confs comes from here, so it will need an independent structure
            mkdir -p "$direlegido/.config/xpad"
            cp -a "${direlegido}/.config.old/xpad/*" "${direlegido}/.config/xpad/"

            mkdir -p "$direlegido/.config/transmission"
            cp -a "${direlegido}/.config.old/transmission/*" "${direlegido}/.config/transmission/" 2>/dev/null
            ;;
        .e)
            # Note: only for root mode (installer upgrade), if is done by the user, ask if want a full update
            cp -a "${direlegido}/.e.old/e/applications/bar/default/.order" "${direlegido}/.e/e/applications/bar/default/.order" 2>/dev/null
            cp -a "${direlegido}/.e.old/e/backgrounds/*" "${direlegido}/.e/backgrounds/" 2>/dev/null
            cp -a "${direlegido}/.e.old/e/themes/*" "${direlegido}/.e/themes/" 2>/dev/null
            ;;
    esac

    if [[ -z "$4" ]] ; then
        chown -R "$3:$3" "$direlegido/$nameconf"
    else
        chown -R "$3:$4" "$direlegido/$nameconf"
    fi

    exit
}

upgradetype(){
    # $2 = conf, $3 = user, $4 = group
    if [[ -n "$2" ]] ; then
        # we unset display because we don't want to show the GUI if we have the enough data to use (refactor this someday)
        unset DISPLAY
        nameconf="$2"
    fi

    if [[ -n "$3" ]] ; then
        upgradefromroot "$@"
        exit
    fi


    # if we have not defined $3 (user) is because we want to upgrade OUR user

    if [[ -n "$DISPLAY" && -f /usr/bin/zenity ]] ; then
        zenity --info --text="$( eval_gettext "Make sure that you have closed the application that you want to upgrade its configuration." )"
    else
        el_warning "$( eval_gettext "Make sure that you have closed the application that you want to upgrade its configuration." )"
    fi

    # select which conf to upgrade
    if [[ -n "$DISPLAY" && -f /usr/bin/zenity ]] ; then
        upgradegraphical "$@"
    else
        upgradeconsole "$@"
    fi

    [[ -z "$nameconf" ]] && { show_message_required_select ; exit 1 ; }
    [[ -e "$HOME/$nameconf.old" ]] && rm -rf "$HOME/$nameconf.old"
    mv "$HOME/$nameconf" "$HOME/$nameconf.old"

    el_warning "copying files from skel by user can give errors from unreadable files"
    if ! cp -a "/etc/skel/$nameconf" "$HOME/$nameconf" ; then
        if [[ -n $DISPLAY && -f /usr/bin/zenity ]] ; then
            zenity --error --text="Not possible to copy the $nameconf to $HOME/$nameconf"
        else
            el_error "Not posible to copy the $nameconf to the $HOME/$nameconf"
            exit 5
        fi
    fi

    case "$nameconf" in
        .config)
            cp -a $HOME/.config.old/xpad/* "$HOME/.config/xpad/"
            cp -a "$HOME/.config.old/transmission" "$HOME/.config/"
            ;;
        .e)
            if [[ -n $DISPLAY && -x /usr/bin/zenity ]] ; then
                if zenity --question --text="$( eval_gettext "Select OK if you want to upgrade your E17 configuration with saving wallpapers, themes, and the bar applications. Select Cancel if you want a full clean upgrade" )" ; then

                    cp -a $HOME/.e.old/e/applications/bar/default/.order $HOME/.e/e/applications/bar/default/.order 2>/dev/null
                    cp -a $HOME/.e.old/e/backgrounds/* $HOME/.e/backgrounds/ 2>/dev/null
                    cp -a $HOME/.e.old/e/themes/* $HOME/.e/themes/ 2>/dev/null
                fi
            fi
            ;;
    esac

    convert_dir "$USER" "$HOME/$nameconf"

    chown -R "$USER" "$HOME/$nameconf"
    chgrp -R "$USER" "$HOME/$nameconf"

    show_message_done
}

usermode(){
    # (re)-add all the files from skel to the user home and migrates them (warning!)
    # $2 = user, $3 = group
    local direlegido
    [[ ! "$UID" == "0" ]] && { echo -e "You need root for this option, warning" && exit 1 ; }
    [[ -z "$2" ]] && { echo -e "No USERNAME parameter in \$2, exiting..." && exit 1 ; }

    # note: root is not in DHOME
    direlegido="$( awk -v usuario="$2" 'BEGIN{FS=":"}{if ($1 == usuario) print $6 }' /etc/passwd )"
    cd "$direlegido" || { echo "Not posible to enter in the HOME dir of $2" ; exit 4 ; }

    # loop and re-import (wiping out) all the matches from skel
    while read -ru 3 line
    do
        if el_check_variables "line" ; then
            el_debug "deleting and re-importing $line for $2"

            if [[ -d "$direlegido/${line}" ]] ; then
                rm -rf "${direlegido}/${line}.old"
                mv "${direlegido}/${line}" "${direlegido}/${line}.old"
            fi

            cp -a "/etc/skel/$line" "$direlegido/$line"

            # fix permissions
            if [[ -z "$3" ]] ; then
                chown -R "$2:$2" "$direlegido/$line"
            else
                chown -R "$2:$3" "$direlegido/$line"
            fi
        fi
    done 3<<< "$( ls -a1 /etc/skel/ | awk 'NR > 2' | grep -vE "^(Desktop|Downloads|Documents|Images|Music|Videos|Public)$"  )"

    # append some files
    # Note: No more needed: they will be added as links when new user creation dynamix startup scripts time (user-manager/deliver)
    #cp -a /etc/skel/{Downloads,Documents,Images,Music,Videos,Desktop} "$direlegido/"
    #for file in Downloads Documents Images Music Videos Desktop
    #do
        ## fix permissions
        #if [[ -z "$3" ]] ; then
            #chown -R "$2:$2" "$direlegido/$file"
        #else
            #chown -R "$2:$3" "$direlegido/$file"
        #fi
    #done

    # fix addresses
    convert_all_files "$2"

}

#===  FUNCTION  ================================================================
#          NAME:  convert_dir
#   DESCRIPTION:  convert all the files found
#    PARAMETERS:  $1 = user-to, $2 = target
#       RETURNS:
#===============================================================================
convert_dir(){
    # pre {{{
    local user target file
    el_debug
    el_security_function_loop 20 || return

    username="$1"
    target="$2"
    el_check_variables "username,target,defaultuser"

    if ! [[ -d "$target" ]] ; then
        if [[ -f "$target" ]] ; then
            sed -i "s|$defaultuser|$username|g" "$target"
        else
            el_debug "$target is not a dir? ignoring..."
            return
        fi
    fi

    # }}}

    # only for the files found in skel
    while read -ru 3 file
    do
        if grep -qs "$defaultuser" "$file" ; then
            sed -i "s|$defaultuser|$username|g" "$file"
            el_debug "exporting configurations for user $username and file $file"
        fi
    done 3<<< "$( find "$target" -type f | grep -viE "\.(mp3|avi|mpg|wav|ogg|mkv|torrent|pdf|epub|doc|jpg|odt)$" )"

    # rename files / dirs
    while read -ru 3 file
    do
        if [[ "$file" = *"${defaultuser}"* ]] ; then
            # FIXME: perl dependency
            rename "s|$defaultuser|$username|" "$file"

            el_debug "renaming $file with $username"
        fi
    done 3<<< "$( find "$target" )"

    # fix permissions, if chagned
    chown -R "$username" "$target"
    chgrp -R "$username" "$target"

}

#===  FUNCTION  ================================================================
#          NAME:  convert_all_files
#   DESCRIPTION:  convert all the files found
#    PARAMETERS:  $1 = user-to
#       RETURNS:
#===============================================================================
convert_all_files(){
    # pre {{{
    local user target file direlegido
    el_debug
    el_security_function_loop 20 || return

    username="$1"
    direlegido="$( awk -v usuario="$username" 'BEGIN{FS=":"}{if ($1 == usuario) print $6 }' /etc/passwd )"
    el_check_variables "username,defaultuser"

    # }}}

    # only for the files found in skel
    while read -ru 3 file
    do
        file="${file#/etc/skel/}"
        sed -i "s|$defaultuser|$username|g" "$direlegido/$file"

        # fix permissions, if chagned
        chown -R "$username" "$direlegido/$file"
        chgrp -R "$username" "$direlegido/$file"

        el_debug "exporting configurations for user $username and file $file"
    done 3<<< "$( find /etc/skel -type f | grep -viE "\.(mp3|avi|mpg|wav|ogg|mkv|torrent|pdf|epub|doc|jpg|odt)$" )"

}

#===  FUNCTION  ================================================================
#          NAME:  restore_user_confs
#   DESCRIPTION:  restore some important user configurations that we don't want to remove
#    PARAMETERS:  $1 = user, [$2 = conf(s)]
#                   confs is optional, space/comma-separated entries
#       RETURNS:  -
#===============================================================================
restore_user_confs(){
    # pre {{{
    local user confs conf
    el_debug
    el_security_function_loop || return

    user="$1"
    confs="$2"
    el_check_variables "user"

    if [[ -z "$confs" ]] ; then
        confs="$( ls -a1 /etc/skel | awk 'NR > 2' | grep -vE "^(Desktop|Downloads|Documents|Images|Music|Videos|Public)$" | sort -u )"
    fi

    # }}}
    while read -ru 3 conf
    do
        echo "d: '$conf'"
    done 3<<< "$( echo "$confs" | tr ' ' '\n' | tr ',' '\n' )"

}


alltype(){
    # run from root, no ptions, it changes all the keywords of eliveuser to the new user in every home, warning!
    local file i

    [[ "$UID" == "0" ]] || { echo -e "You need root for this option" && exit 1 ; }

    cd "${DHOME}"
    #for i in `ls -1`
    for i in $(find "$DHOME" -mindepth 1 -maxdepth 1 -type d )
    do
        username="$( basename "$i" )"
        if [[ "$username" = "eliveuser" ]] ; then
            continue
        fi
        # user exist?
        if ! grep -qs "^${username}:" /etc/passwd ; then
            continue
        fi
        #echo "exporting configurations from the user $defaultuser to ${username}..."

        convert_all_files "$username"

        # rename files / dirs
        while read -ru 3 file
        do
            if [[ "$file" = *"${defaultuser}"* ]] ; then
                # FIXME: perl dependency
                rename "s|$defaultuser|$username|" "$file"

                el_debug "renaming $file with $username"
            fi
        done 3<<< "$( find "$DHOME/$username" )"
    done
}

addmode(){
    # $1 = (mode), $2 = conf, $3 = username
    if [[ -z $3 ]] ; then
        echo -e "Usage: `basename $0` (add) conf username"
        exit
    fi
    if [[ "$UID" != 0 ]] ; then
        el_error "Need to be root"
        exit 1
    fi
    direlegido="$( awk -v usuario="$3" 'BEGIN{FS=":"}{if ($1 == usuario) print $6 }' /etc/passwd )"

    if [[ ! -d "$direlegido" ]] ; then
        el_error "User not exists?"
        exit
    fi

    #el_warning "copying files from skel by user can give errors from unreadable files"
    #su -c "cp -a '/etc/skel/$2' '$direlegido/'" "$3"

    cp -a "/etc/skel/$2" "$direlegido/"
    convert_dir  "$3" "$direlegido/$2"
    chown -R "$3:$3" "$direlegido/$2"

    el_explain 0 "Conf of $2 added to user $3"
}



#-------------------------------------------------------------------------------
#   Interactive tools, does the work
#-------------------------------------------------------------------------------
interactive_tools(){
    id="$1"
    homeid="${HOME}/${id}"

    [[ ! -e "$homeid" ]] && { zenity --error --text="Not found $homeid, nothing to upgrade?" ; return 1 ; }
    rm -rf "${homeid}.old" 2>/dev/null
    mv "${homeid}" "${homeid}.old"

    el_warning "copying files from skel by user can give errors from unreadable files"
    if ! cp -a "/etc/skel/${id}" "$homeid" ; then
        zenity --error --text="Error found by copy '$id' to the user"
        exit 1
    fi

    convert_dir "$USER" "$homeid"

    #find "$homeid" -type f -exec sed -i "s,${DHOME}/${defaultuser},${HOME},g" '{}' \;
    #find "$homeid" -type f -exec sed -i "s,${defaultuser},${USER},g" '{}' \;
    chown -R "$USER" "$homeid"
    chgrp -R "$USER" "$homeid"
}
#-------------------------------------------------------------------------------
#   Interactive mode, like upgrade but translated and descriptible
#-------------------------------------------------------------------------------
interactive(){
    # improve this crap, someday
    [[ "$UID" = "0" ]] && { echo -e "Root not allowed for this option" ; return ; }
    [[ ! -d "$HOME" ]] && { echo -e "E: Home is not a dir" ; return ; }

    result="$( echo -e \
        "E17\n""$( eval_gettext "Your Desktop. Includes minimizer, pager, bar, features, and all the gadgets" )""\n"\
        "E17 Confs\n""$( eval_gettext "Your Desktop. Only configurations (doesn't include wallpapers, themes, etc)" )""\n"\
        "Thunar\n""$( eval_gettext "Your File manager and Browser. Includes features and actions" )""\n"\
        "Bash\n""$( eval_gettext "Bash (shell) Configurations" )""\n"\
        "Compiz\n""$( eval_gettext "Compiz (ecomorph) configurations" )""\n"\
        "Terminal\n""$( eval_gettext "Terminal configurations" )""\n"\
        "Web\n""$( eval_gettext "Web Browser (Firefox)" )""\n"\
        "Menus\n""$( eval_gettext "Menus of Applications" )""\n"\
        "Mplayer\n""$( eval_gettext "Media Player" )""\n"\
        "Theme\n""$( eval_gettext "Themes of some applications (gtk, qt and kde)" )""\n"\
        "Other\n""$( eval_gettext "Other configuration not listed here" )""\n"\
        "Exit\n""$( eval_gettext "Exit from here" )" \
        | zenity --list --text="$( eval_gettext "Select a configuration that you want to restore" )" --column="$( eval_gettext "Action" )" --column="$( eval_gettext "Description" )" --width="600" --height="420" || echo cancel )"

    case $result in
        E17)
            interactive_tools ".e"
            sleep 1 ; zenity --info
            ;;
        "E17 Confs")
            interactive_tools ".e/e/config"
            sleep 1 ; zenity --info
            ;;
        Thunar)
            interactive_tools ".config/Thunar"
            sleep 1 ; zenity --info
            ;;
        Bash)
            interactive_tools ".bash_logout"
            interactive_tools ".bashrc"
            interactive_tools ".bash_profile"
            sleep 1 ; zenity --info
            ;;
        Compiz)
            interactive_tools ".ecomp"
            sleep 1 ; zenity --info
            ;;
        Terminal)
            interactive_tools ".Xdefaults"
            sleep 1 ; zenity --info
            ;;
        Web)
            interactive_tools ".mozilla"
            sleep 1 ; zenity --info
            ;;
        Menus)
            interactive_tools ".config/menus"
            interactive_tools ".local/share/applications"
            interactive_tools ".local/share/desktop-directories"
            sleep 1 ; zenity --info
            ;;
        Mplayer)
            interactive_tools ".mplayer"
            sleep 1 ; zenity --info
            ;;
        Theme)
            interactive_tools ".qt"
            interactive_tools ".gtkrc"
            interactive_tools ".gtkrc-2.0"
            interactive_tools ".gtkrc.mine"
            interactive_tools ".kde"
            interactive_tools ".kderc"
            sleep 1 ; zenity --info
            ;;
        Other)
            upgradetype
            ;;
        cancel|Exit)
            return 0
            ;;
        *)
            echo "Option not recognized"
            true
            ;;
    esac

    interactive
}

# Usage
usage(){
    echo -e "Usage: $(basename $BASH_SOURCE) options:"
    echo -e "Use: \"elive-skel all\" for ADAPT the configurations for all users (should be already imported)"
    echo -e "Use: \"elive-skel upgrade [conf] [user] [group]\"  for UPGRADE your configuration or another user"
    echo -e "        if no user is set, it upgrades it to your user, if no conf is set, it asks you interactively"
    echo -e "Use: \"elive-skel interactive: it asks you graphically/interactive a configuration to upgrade (re-import), removing old one"
    echo -e "Use: \"elive-skel user username [group]\" re-import all the default configurations of username, removing old ones (warning)"
    echo -e "Use: \"elive-skel add conf username\" for ADD configurations/files, like a upgrade but just updating it without remove other things"
    exit 1
}

if [[ -z "${1}" ]] ; then
    usage
fi



#-------------------------------------------------------------------------------
#   Main selector
#-------------------------------------------------------------------------------


case "$1" in
    upgrade|-upgrade|--upgrade) upgradetype "$@"
        ;;
    interactive) interactive "$@"
        ;;
    all|-all|--all) alltype "$@"
        ;;
    user|-user|--user) usermode "$@"
        ;;
    add|-add|--add) addmode "$@"
        ;;
    *)
        usage
        ;;

esac



# vim: set foldmethod=marker :

