#!/bin/bash
### BEGIN INIT INFO
# Provides:          nurse
# Required-Start:    dbus
# Required-Stop:     dbus
# Should-Start:
# Should-Stop:
# Default-Start:     2
# Default-Stop:      1
# Short-Description: Nurse mode
# Description:       Special recovery Elive tool
### END INIT INFO



case "$1" in
    start)
        # disabled, not implemented for 3.0
        true
        #if grep -q nurse /proc/cmdline ; then
            #su -l -c "/usr/share/nurse/lib/nurse-pre-x.sh"
        #fi
        ;;
    stop)
        true
        ;;
    *)
        true
        ;;
esac


